elasticSearchItemsUrl: http://localhost:9200/recipe/items
elasticSearchUsersUrl: http://localhost:9200/recipe/users
prefixAdjustmentsPath: ~/recipes/src/main/resources/prefixAdjustments.txt
suffixAdjustmentsPath: ~/recipes/src/main/resources/suffixAdjustments.txt
cuisineColoursPath: ~/recipes/src/test/resources/cuisineColours.json

elasticsearch:
  host: localhost
  port: 9300
  settingsPath: ~/recipes/src/main/resources/index.yaml
  mappings:
    items:
      path: ~/recipes/src/main/resources/esItemsMappingsAutocomplete.json
    recipes:
      path: ~/recipes/src/main/resources/esRecipesMappingsAutocomplete.json

loader:
  items:
    path: ~/recipes/src/test/resources/inputs.yaml
  bbcgoodfood:
    path: ~/recipes/src/test/resources/ingredients/bbcgoodfood
  curryfrenzy:
    path: ~/recipes/src/test/resources/ingredients/curryfrenzy
