/**
 * 
 */
package uk.co.recipes.api;

/**
 * TODO
 *
 * @author andrewregan
 *
 */
public enum Units implements IUnit {

	INSTANCES,

	KG, GRAMMES, POUNDS, OUNCES, ML, CM, INCH, MM,

	TSP, HEAPED_TSP, ROUNDED_TSP,
	TBSP, HEAPED_TBSP, ROUNDED_TBSP,

	DASH, FEW, LITTLE, SPLASHES, DRIZZLE, SQUEEZE,

	BUNCHES, BIG_BUNCHES, SMALL_BUNCHES, DROP, HANDFUL, PINCH, BIG_PINCH, KNOB, CLOVE, STICK, PIECE, GLASS, CUP, POT, JAR, PACKET, QUART, LITRE
}